# -*- coding: utf-8 -*-
# ---------------------------------------------------------------
# Assignment3Script.py
# ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp Created on: 2019-10-20 .3
#   (generated by ArcGIS/ModelBuilder)
# Description: This script is the process for doing a weighted
# overlay where each weight is worth 50%. In this case, it is the
# SlopeCost = 50% and the LandUseCost = 50%
# ---------------------------------------------------------------

# Import arcpy module, this add all of the ArcGIS function to
# Python, they are not incldued by default. ArcGIS must be installed
# on the computer you use this script with.
import arcpy

# We need to make sure we have the Spatial Analyst Extension Checked
arcpy.CheckOutExtension("Spatial")

# Local variables:
# First we will define our existing raster files files
# Note: We will save the path to the files as a variable so we
# Only need to enter this information once, and we will concatenate
# Additonal strings to create variables with the names
# This path value needs to be changed according to your local path settings!!!
path = "C:\Users\HP\Desktop\GGR321_Assignment-3 Data (1)\GGR321_Assignment-3 Data\Part3\\"

# The location of the trailhead
TrailHead = path + "TrailHead.shp"

# Your selected best sightseeing location in the last step as the destination
# You need to change the file name from "CandidateSpot_C" to the name of the best sightseeing location
# CandidateSpot_C
Destination = path + "CandidateSpot_X.shp"

# The Slope Cost Raster that you created
# You may need to change the file name
# If it is inside a folder you need to include the folder e.g.
# "foldername\\filename.tif"
SlopeCost = path + "Slope_Cost.tif"

# The Land Use Cost Raster that you created
# You may need to change the file name
LandCost = path + "LandUse_Cost1.tif"

# Now we will define file names that we will use
# when we create new files.

# Hint: When you add the for loop, these files names
# will need additional variables to allow you to store
# multiple files.
# Example if you use s and l as your indexed values
slope = [10,20,30,40,50,60,70,80,90]
landuse =[10,20,30,40,50,60,70,80,90]
for x in range(9):
    s = slope[x]
    l = landuse[x]
    CostDist_tif = path + "CostDist_"+"s+_"+"l.tif"

# You can choose to delete the temporary files in the process


# This is the file name for our weighted SlopeCost
tSLC_tif = path + "tSLC.tif"

# This is the file name for our weighted LandUse Cost
tLCC_tif = path + "tLCC.tif"

# File name for the combined weighted file
Cost_tif = path + "Cost.tif"

# Cost Distance
CostDist_tif = path + "CostDist.tif"

# Cost Back Link
CostDist_bl_tif = path + "CostDist_bl.tif"

# Least Cost Path
LeastPath_tif = path + "LeastPath.tif"

# Polygon from converting cost path to shapefile
LeastPath_poly = path + "LeastPathPoly.shp"



# Process:

# Instead of Weighted Overlay, this approach multiples each
# raster by a weight (that equals 1) and then adds the two
# weighted rasters together

# Process: Times for Slope
# Used to multiple the slope cost by the weight
# In your code, the 0.5 will need to be changed to a variable
tSLC_tif = arcpy.sa.Times(0.5, SlopeCost)

# Process: Times for land cover
# Used to multiple the land cover cost by the weight
tLCC_tif = arcpy.sa.Times(0.5, LandCost)

# Process: Plus
# Used to add the two weighted costs together for the cost surface
Cost_tif = arcpy.sa.Plus(tSLC_tif, tLCC_tif)

# Process: Cost Distance
CostDist_tif = arcpy.sa.CostDistance(TrailHead, Cost_tif,"", CostDist_bl_tif, "", "", "", "", "")

# Process: Cost Path
LeastPath_tif = arcpy.sa.CostPath(Destination, CostDist_tif, CostDist_bl_tif, "EACH_CELL", "Id")

# Process: Raster to Polyline
arcpy.RasterToPolyline_conversion(LeastPath_tif, LeastPath_poly, "ZERO", "0", "SIMPLIFY", "Value")
