# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Script.py
# Created on: 2020-11-21 01:32:04.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

#Import acrcpy is used to import the ArcGIS framework for python
#TO have access to all ArcGIS tools in python
import arcpy

#This follow code are used to Get aach parameter of the process that the
# script works for

Input__Feature = arcpy.GetParameterAsText(0)
Feature_ToPoint = arcpy.GetParameterAsText(1)
Distance_value_or_Field = arcpy.GetParameterAsText(2)
Point_Buffer_Name = arcpy.GetParameterAsText(3)



#Local variable
# Point_Feature is used to store the base file for the tools
Point_Feature = "F:\Lab3Data\Lab3Data\Assignment_Data.shp"


#Process: Feature To Point
# This FetureTopoint tools is used to convert Feature class data to point

arcpy.FeatureToPoint_management(Point_Feature, Feature_ToPoint,"CENTROID")
arcpy.AddMessage("Coverting Feature to Point")

#Process: Buffer
# The buffer tools is used to set a boundary or encroachment around the points
# that are output of the featureTo point
arcpy.Buffer_analysis(Feature_ToPoint, Point_Buffer_Name, Distance_value_or_Field, "FULL", "ROUND", "NONE", " ", "PLANAR" )

#This AddMessage is used to add message to show which tools is running
arcpy.AddMessage("Buffering Points")
