#-*- coding: utf-8 -*-
# ---------------------------------------------------------------
# ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp Created on: 2019-10-20 .3
#   (generated by ArcGIS/ModelBuilder)
# Description: This is an independent Script that accepts a user input slope in degree
# and returns the estimated Walking speed from Tobler's equation.

#The math module is imported to get mathematical function such as pi
from math import pi

# Enter the Value of your slope in degree
Slope = int(input('Enter Your slope value: '))

#Where W= Walking Velocity[km/h]

#The formula below is  the Tober's Hiking Function
W = 6*(2.71828)**(-3.5)*abs((Slope)*(pi/180)+0.05)

print( "Walking Velocity =  ",W)
